import { Booking } from "@/types";
import { MOCK_PROVIDERS } from "./providers";

const aliUsta = MOCK_PROVIDERS.find((p) => p.id === "ali-karimov")!;
const akmalUsta = MOCK_PROVIDERS.find((p) => p.id === "akmal-jorayev")!;

export const MOCK_BOOKINGS: Booking[] = [
  {
    id: "booking-8942",
    orderNumber: "UT-8942",
    requestId: "req-8942",
    quoteId: "quote-1",
    customerId: "user-sardor",
    customerName: "Sardor A.",
    customerPhone: "+998 90 987-65-43",
    provider: aliUsta,
    serviceName: "Konditsioner ta’miri va freon to‘ldirish",
    totalPrice: 230000,
    status: "IN_TRANSIT",
    statusText: "Usta yo‘lda",
    scheduledTime: "Bugun 18:00",
    estimatedArrival: "17:50",
    estimatedMinutesLeft: 10,
    vehicle: {
      model: "Cobalt",
      color: "oq",
      plateNumber: "01 A 777 BA",
    },
    destinationAddress: "Toshkent sh., Chilonzor tumani, 9-mavze, 14-uy, 28-xonadon",
    distanceKm: 2.4,
    timeline: [
      {
        title: "Buyurtma yaratildi",
        subtitle: "15:20 da ro‘yxatga olindi",
        timestamp: "15:20",
        completed: true,
        current: false,
      },
      {
        title: "Usta tasdiqladi",
        subtitle: "15:35, Ali Karimov",
        timestamp: "15:35",
        completed: true,
        current: false,
      },
      {
        title: "Usta yo‘lda",
        subtitle: "10 daqiqa qoldi",
        timestamp: "17:35",
        completed: false,
        current: true,
      },
      {
        title: "Ish boshlandi",
        subtitle: "Kelgandan so‘ng",
        timestamp: "--:--",
        completed: false,
        current: false,
      },
      {
        title: "Tugash va baholash",
        subtitle: "Xizmat yakunida",
        timestamp: "--:--",
        completed: false,
        current: false,
      },
    ],
    paymentMethod: "ESCROW",
    isPaid: false,
    createdAt: "2026-09-13T15:20:00Z",
  },
  {
    id: "booking-8941",
    orderNumber: "UT-8941",
    requestId: "req-8941",
    quoteId: "quote-prev",
    customerId: "user-sardor",
    customerName: "Sardor A.",
    customerPhone: "+998 90 987-65-43",
    provider: akmalUsta,
    serviceName: "Oshxona krani ta'mirlash",
    totalPrice: 150000,
    status: "COMPLETED",
    statusText: "Bajarildi",
    scheduledTime: "12-sentyabr, 11:00",
    estimatedArrival: "11:00",
    estimatedMinutesLeft: 0,
    vehicle: {
      model: "Lacetti",
      color: "kulrang",
      plateNumber: "01 B 456 AA",
    },
    destinationAddress: "Toshkent, Yunusobod 4-mavze",
    distanceKm: 4.1,
    timeline: [
      {
        title: "Buyurtma yaratildi",
        subtitle: "10:00",
        timestamp: "10:00",
        completed: true,
        current: false,
      },
      {
        title: "Usta tasdiqladi",
        subtitle: "10:15",
        timestamp: "10:15",
        completed: true,
        current: false,
      },
      {
        title: "Usta yo‘lda",
        subtitle: "10:30",
        timestamp: "10:30",
        completed: true,
        current: false,
      },
      {
        title: "Ish boshlandi",
        subtitle: "11:00",
        timestamp: "11:00",
        completed: true,
        current: false,
      },
      {
        title: "Tugash va baholash",
        subtitle: "11:45 da yakunlandi",
        timestamp: "11:45",
        completed: true,
        current: true,
      },
    ],
    paymentMethod: "CARD",
    isPaid: true,
    createdAt: "2026-09-12T10:00:00Z",
  },
];
