import { ServiceCategory } from "@/types";

export const MOCK_CATEGORIES: ServiceCategory[] = [
  {
    id: "santexnika",
    slug: "santexnika",
    name: "Santexnika",
    description: "Kranlar, quvurlar, vanna va unitaz o‘rnatish",
    iconName: "Wrench",
    mastersCount: 420,
    featured: true,
  },
  {
    id: "elektrik",
    slug: "elektrik",
    name: "Elektrik",
    description: "Simlar almashtirish, lyustra, avtomat va rozetkalar",
    iconName: "Zap",
    mastersCount: 380,
    featured: true,
  },
  {
    id: "konditsioner",
    slug: "konditsioner",
    name: "Konditsioner",
    description: "Freon quyish, yuvish, montaj va ta'mirlash",
    iconName: "Snowflake",
    mastersCount: 290,
    featured: true,
  },
  {
    id: "maishiy-texnika",
    slug: "maishiy-texnika",
    name: "Maishiy texnika",
    description: "Kir yuvish mashinasi, muzlatgich, gaz plitalari",
    iconName: "Tv",
    mastersCount: 510,
    featured: true,
  },
  {
    id: "remont",
    slug: "remont",
    name: "Remont va pardozlash",
    description: "Gipsokarton, kafel, kafel terish va pol yotqizish",
    iconName: "Paintbrush",
    mastersCount: 340,
    featured: true,
  },
  {
    id: "tozalash",
    slug: "tozalash",
    name: "Tozalash / Klining",
    description: "Uylar, ofislar, derazalar va gilam tozalash",
    iconName: "Sparkles",
    mastersCount: 210,
    featured: true,
  },
  {
    id: "mebel",
    slug: "mebel",
    name: "Mebel yig‘ish",
    description: "Shkaflar, oshxona garnituri, mebel ta'mirlash",
    iconName: "Armchair",
    mastersCount: 180,
    featured: true,
  },
  {
    id: "kochirish",
    slug: "kochirish",
    name: "Ko‘chirish va yuk",
    description: "Xonadon ko‘chirish, yuk tashuvchilar va transport",
    iconName: "Truck",
    mastersCount: 160,
    featured: true,
  },
];
