import { Provider } from "@/types";

export const MOCK_PROVIDERS: Provider[] = [
  {
    id: "ali-karimov",
    slug: "ali-karimov",
    name: "Ali Karimov (Ali Usta)",
    title: "Konditsionerlar bo'yicha yetakchi muhandis • 8 yillik faoliyat",
    shortTitle: "Ali Usta",
    avatar: "https://lh3.googleusercontent.com/aida-public/AB6AXuDEO8_6X8DRH3xqwrD2kgZ85JlrP3AQ8150pmUGfRFpA85-WD6tL7Gk0lDa4E_I3MJOpBNkh5vdZhKrd41_XgH_xB2TIPgdWySzbjVWEJQxWFtrXChbM8JE7CuH2j3SOX_8KQchAZkJvLrLxYVSfxXzFFpiCg7wUWjZUxV-eCeCAlZOctBffFZmGIJAQZ2gHa_LdeRbRAMfBqettSQFbvjgLwhRCdw64S0XH6oanNdKJbUODaRXrTjv6w",
    coverImage: "https://lh3.googleusercontent.com/aida-public/AB6AXuClv5k6ZHlSJABG5tCAg0LKR3wDg7txCRnuz44M0A0RlNFEa3v7yKAz9_p2vGoxAfanewLDhlbqYgw4Jeu6sKvHgcN-NLUEd8yeFkJoRndlBlj2mFMpyleGuXHFzlxDu2xD4auJ9G9gt2rlJ8g52rGTOGA3ncwUfGB_6k1zmcBzmhppPc_BH6ZVxSMoGRC4F3HGGlyhXWy3zOv6_SxfwJTvWDkp3vsK7JZL7b06tDE26o0zpr6c701nlg",
    rating: 4.92,
    reviewsCount: 127,
    completedJobsCount: 127,
    experienceYears: 8,
    responseMinutes: 15,
    verified: true,
    phone: "+998 90 123-45-67",
    city: "Toshkent",
    district: "Chilonzor",
    addressFull: "Toshkent, Chilonzor tumani, 9-mavze",
    priceRange: {
      min: 80000,
      max: 250000,
      formatted: "80 000 – 250 000 so‘m",
    },
    distanceKm: 2.3,
    availableTime: "Bugun 17:30 dan bo‘sh",
    isOnline: true,
    matchReason: "Sizning Chilonzor tumaningizga juda yaqin va konditsioner sovutmasligi hamda freon to'ldirish bo'yicha 40+ ijobiy sharhga ega.",
    categoryIds: ["konditsioner", "maishiy-texnika"],
    tags: ["Freon quyish", "Yuvish", "Konditsioner montaj", "Plata ta'miri"],
    warrantyMonths: 6,
    vehicleInfo: {
      model: "Cobalt oq",
      plateNumber: "01 A 777 BA",
    },
    aboutText:
      "8 yildan beri Toshkent shahri bo‘ylab barcha rusumdagi (Artel, Shivaki, Samsung, LG, Gree, Midea va boshqalar) split-tizimlar va inverterli konditsionerlarni ta’mirlab kelaman. Har bir bajarilgan ishga 6 oylik rasmiy yozma kafolat beraman. Ish jarayonida faqat zavod tavsiya etgan sifatli ehtiyot qismlar va toza R410A / R22 freonlaridan foydalanaman.",
    ratingMetrics: {
      quality: 5.0,
      punctuality: 4.9,
      priceFairness: 4.9,
    },
    services: [
      {
        id: "s1",
        name: "Konditsionerni diagnostika qilish",
        description: "Nosozlik sababini aniqlash, bosim va elektr ulanishlarini to‘liq tekshirish",
        price: 80000,
        priceFormatted: "80 000 so‘m",
        badge: "Tuzatilsa bepul",
        iconName: "Search",
      },
      {
        id: "s2",
        name: "Freon quyish (R410A / R22 gaz)",
        description: "Bosim o‘lchagich orqali qochqinlarni aniqlash va original freon to‘ldirish",
        price: 150000,
        priceFormatted: "150 000 – 250 000 so‘m",
        badge: "Hajmiga qarab",
        iconName: "Gauge",
      },
      {
        id: "s3",
        name: "To‘liq yuvish va antibakterial tozalash",
        description: "Ichki va tashqi blokni maxsus karcher, par generatori va kimyoviy eritma bilan dezinfeksiya qilish",
        price: 180000,
        priceFormatted: "180 000 so‘m",
        badge: "Eng ommabop",
        iconName: "Sparkles",
      },
      {
        id: "s4",
        name: "Kompressor yoki elektron plata ta’miri",
        description: "Inverter mikrosxemalarini qayta payvandlash, kondensator almashtirish",
        price: 200000,
        priceFormatted: "200 000 – 400 000 so‘m",
        badge: "Ehtiyot qism alohida",
        iconName: "Cpu",
      },
    ],
    portfolio: [
      {
        id: "p1",
        title: "To‘liq yuvish",
        location: "Chilonzor-7",
        imageUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuDl0ERqENtHb_w8GLZkYJWohCj9tg30oXtccBS3RVs2klVtvBYtbU_G5W8h44KNwHJPxk7qEj3nl-DbbEsKqFth_gEr5aAsgpNWw-D_IS4ShuT8Kh6VodL0_7WDUhij9RwmH-ZCBY_zWIUQlt0CmanfU6403K63ZyPe4WJoLMbWmRxe0DdSo3UxCyMkfQLJeV_32M6jMyVvw7vDCbGeEO0bmhB6LvC3P1ak9DrqXHDRp0ajt4TGL0lYSA",
      },
      {
        id: "p2",
        title: "Freon R410A quyish",
        location: "Yunusobod",
        imageUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuBa_gG1aSeuyQthvJp5bucwKXiKvOcNqdvMS8A_ujCj_CFraMGy6rptmEPujyuaEa1yyJx1HY_f5o32-emqY_A_STcximkBf0c7yerpjfaXJfGey1E5RdEexCrL_PIN2KQOgMAYIYVpSa2CGq4T-Hy6MLeDn7hB7EgNYKxEKOlqTAvQlzZVW25SA4SrOB1BkIzieZCpkSuAHDj3NLjGHa_XIgMGoUBUFE_PxHEYUbWynrj8xTzg8JCdUg",
      },
      {
        id: "p3",
        title: "Ish qurollari & Karcher",
        location: "Maxsus anjomlar",
        imageUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuCmPXgyLnipgS6KxNnhHZ9_MZurHe2p_kR908YpaBv3RZiChzkvzMt4ZUMCfJjSdDOOGAHpdq3eu0QtF_mXrCuzmA1w_RFaX0Lgw9-DDqRmqVy7SZIQr6UOYfovCo51W0Ul9z84h_vF9_CUfcH-m8vWRMdeOg2equaP8VR-oFlwFFuBYmGW0XiHpE4fVdSL4qNiHxIGXEj5TiBJzWDUMjDIk8RnZkE5IGeD4FgrCt_qIT_pSQsHHFzGHg",
      },
      {
        id: "p4",
        title: "Oldin va Keyin holat",
        location: "Mirobod",
        imageUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuDEPFrnJtN2YAtBZFF2SFP3AJlmmOJRrKpGo09fJXf9Cu2WtxSKWpTfM8jXhxpDHE5axrsINIzOBb-INRYhqSRQg1m3waP2r-LdxwWHDJDltgvpzeaOdzm072NRjzZ7nKgd2Az1mqI53OXiPdUUmXvqUOBl8MQDejNiUoo4mYZ5CB3WLisZll3Sm4l4We3lessKqhVEt3Djm0hzYfo8NXO_eRs0DczIG0mRDoJLYXRqPvSGZfFvKMRaAw",
      },
      {
        id: "p5",
        title: "Plata mikrosxema ta’miri",
        location: "Labaratoriya",
        imageUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuCSvbRHFnUNXe9jh6aUDB6lylXlqJctrK91mXczZ_dBr0SBKWESmFLSkpegB4TDLSdtVsI4v34ccUfTqnWDRoUKCbNa4fybmaNkTrYBo7U14wnlmloW5528nGMlLGZIQmE-sjFhFwmI3cjfXhn4GRgqAjnlKI7FDgaMmgxEG-nY9g0L11WTDa5OuSuop2zIvnRswLmJWCud3afpmKODTAJ8DhcsmXC9xtUoaZ6DzZorM7bo5-gVPWspYQ",
      },
      {
        id: "p6",
        title: "Konditsioner montaj",
        location: "Chilonzor-9",
        imageUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuAx7HOXO_02PtUgF9bWUa9L6eAT7DyFLfVAFRXIbloqV2CTFC7Zwp7K4SbKorGWIslLI7tHDf7mUwevcgaP12l_eaWN_QOumPx7KPWy36XpKxKRJAs737uQ_IkH15CdcQ5ee4IeSaQm7u6sOzOuHkMx2qCigNEqyGsnoWbdAuy6BCRLHf7EzAxuDXsHq6By8uW5WQr5I-tmqL6fF3HhaWhzXzL1oSuPFGSPjO8C__gqkOo_2MF8nMNxIA",
      },
    ],
    reviews: [
      {
        id: "r1",
        userName: "Javohir Tursunov",
        rating: 5.0,
        comment:
          "Ali usta aytilgan vaqtda aniq keldi, 40 minutda freon quyib, filtrlarni tozalab berdi. Konditsioner muzdek puflamoqda. Juda tez, tartibli va sifatli ishladi. Rahmat!",
        date: "2 kun oldin",
        serviceTitle: "Freon quyish & Yuvish",
        location: "Chilonzor, 9-mavze",
      },
      {
        id: "r2",
        userName: "Nodira Mansurova",
        rating: 5.0,
        comment:
          "Juda xushmuomala usta ekan, toza ishladi, karcher bilan yuvganda polga umuman suv tomizmadi, o‘zidan keyin barcha chiqindilarni yig‘ishtirdi. Kafolat kvitansiyasi ham berdi. Tavsiya qilaman!",
        date: "O‘tgan hafta",
        serviceTitle: "Antibakterial tozalash",
        location: "Mirzo Ulug‘bek tumani",
      },
    ],
  },
  {
    id: "rustam-xoliqov",
    slug: "rustam-xoliqov",
    name: "Rustam Xoliqov",
    title: "Konditsioner montaj va ta'mirlash ustasi",
    shortTitle: "Rustam Usta",
    avatar: "https://lh3.googleusercontent.com/aida-public/AB6AXuCJmg8aBqyFN7mqJRpUVe0_V9RGYXUsvuxEczsEJopH2OQ9i8xKq7PMKXK9teACB_0_xEV3X3M-9NUNfxx2pbvgP1JQJUsMNeCghxCUYWfleOSjbmURBoywj_fa05Y8h3bPfXPuybcrAGHe5Bz7WwaoC8djAtgF485l44TC_JQytHrfYgTOsFbcF3iyzFg076LnqoJWQopEEo7uvuaBotdLJQ25vlN4ge-zUxkKk8jVfWQg69TltO_EIQ",
    coverImage: "https://lh3.googleusercontent.com/aida-public/AB6AXuClv5k6ZHlSJABG5tCAg0LKR3wDg7txCRnuz44M0A0RlNFEa3v7yKAz9_p2vGoxAfanewLDhlbqYgw4Jeu6sKvHgcN-NLUEd8yeFkJoRndlBlj2mFMpyleGuXHFzlxDu2xD4auJ9G9gt2rlJ8g52rGTOGA3ncwUfGB_6k1zmcBzmhppPc_BH6ZVxSMoGRC4F3HGGlyhXWy3zOv6_SxfwJTvWDkp3vsK7JZL7b06tDE26o0zpr6c701nlg",
    rating: 4.95,
    reviewsCount: 84,
    completedJobsCount: 84,
    experienceYears: 6,
    responseMinutes: 8,
    verified: true,
    phone: "+998 93 456-78-90",
    city: "Toshkent",
    district: "Mirzo Ulug‘bek",
    addressFull: "Toshkent, Mirzo Ulug‘bek tumani, Qorasuv",
    priceRange: {
      min: 100000,
      max: 300000,
      formatted: "100 000 – 300 000 so‘m",
    },
    distanceKm: 3.1,
    availableTime: "Bugun 19:00 dan bo‘sh",
    isOnline: true,
    matchReason: "Gree va Artel rasmiy xizmat ko'rsatish markazlarida 4 yillik tajribasi bor",
    categoryIds: ["konditsioner"],
    tags: ["Elektromontaj", "Shchit yig‘ish", "Smart Home", "Freon quyish"],
    warrantyMonths: 3,
    aboutText: "Rasmiy servis markazlarida o'qigan sertifikatlangan usta. Gree, Artel, Midea split-tizimlariga 100% kafolatli xizmat.",
    ratingMetrics: {
      quality: 4.9,
      punctuality: 5.0,
      priceFairness: 4.8,
    },
    services: [],
    portfolio: [],
    reviews: [],
  },
  {
    id: "jamshid-elektrik",
    slug: "jamshid-elektrik",
    name: "Jamshid Elektrik & Konditsioner",
    title: "Katta toifali elektromontajchi va iqlim texnikasi ustasi",
    shortTitle: "Jamshid Usta",
    avatar: "https://lh3.googleusercontent.com/aida-public/AB6AXuA8VWVE3KX9MNNC-tJnM2u2MzhDzypWpnqGNw-o6SCrRXj_lU4uRj7OEznEwzH8r5AWIjIHRIbtS6NBHsB57GElKuf8AzyAAISl-4E0BRUCFuAA17aktTPZgUvYeumZqy_UFtXzyF1UTMMH_HvlPEjlBtdxoTWrsdTHAOYwQ-sXnTtysWHFPMSt9zp3ilB2HZeQQyclnZ-hlZSni2k5Bw8jZ5ZtrskG5IxJkoYBOIeGj4plVx4O7tenKQ",
    coverImage: "https://lh3.googleusercontent.com/aida-public/AB6AXuClv5k6ZHlSJABG5tCAg0LKR3wDg7txCRnuz44M0A0RlNFEa3v7yKAz9_p2vGoxAfanewLDhlbqYgw4Jeu6sKvHgcN-NLUEd8yeFkJoRndlBlj2mFMpyleGuXHFzlxDu2xD4auJ9G9gt2rlJ8g52rGTOGA3ncwUfGB_6k1zmcBzmhppPc_BH6ZVxSMoGRC4F3HGGlyhXWy3zOv6_SxfwJTvWDkp3vsK7JZL7b06tDE26o0zpr6c701nlg",
    rating: 4.8,
    reviewsCount: 210,
    completedJobsCount: 210,
    experienceYears: 10,
    responseMinutes: 12,
    verified: true,
    phone: "+998 94 987-65-43",
    city: "Toshkent",
    district: "Shayxontohur",
    addressFull: "Toshkent, Shayxontohur tumani",
    priceRange: {
      min: 70000,
      max: 200000,
      formatted: "70 000 – 200 000 so‘m",
    },
    distanceKm: 4.5,
    availableTime: "Ertaga 09:00 dan bo‘sh",
    isOnline: false,
    matchReason: "Konditsioner elektr platalarini joyida qayta ta'mirlash bo'yicha mutaxassis",
    categoryIds: ["elektrik", "konditsioner"],
    tags: ["Tezkor chaqiruv", "Plata ta'miri", "Konditsioner montaj"],
    warrantyMonths: 3,
    aboutText: "10 yillik tajribaga ega usta. Elektr platalar va murakkab sovutish nuqsonlarini hal qilish.",
    ratingMetrics: {
      quality: 4.8,
      punctuality: 4.7,
      priceFairness: 5.0,
    },
    services: [],
    portfolio: [],
    reviews: [],
  },
  {
    id: "akmal-jorayev",
    slug: "akmal-jorayev",
    name: "Akmal Jo‘rayev",
    title: "Bosh Santexnik • 9 yillik tajriba",
    shortTitle: "Akmal Usta",
    avatar: "https://lh3.googleusercontent.com/aida-public/AB6AXuAD-R03XzmEait4cjqXjfe2mzd_IuZ0XkcrFWeKwR9b4xJPOXcNUvLp9lm6LN7yMjgWapFemFG7of5Pwgxv2_FP5oKEjya-x5WW1PlxhDYbVuxY3WTQmNuuruoOpHQJrmUVIxW011MUmTd_Wp8AT0y-B8EqbIBtNEMqlCbvLKj3qOf79m14PSlNAY5P6Tn35KAH2DOZFCWlrZ1xlYz68QT9W9kmeS0AHPRSErRwovKkY3-maHuBJ5fKpg",
    coverImage: "https://lh3.googleusercontent.com/aida-public/AB6AXuClv5k6ZHlSJABG5tCAg0LKR3wDg7txCRnuz44M0A0RlNFEa3v7yKAz9_p2vGoxAfanewLDhlbqYgw4Jeu6sKvHgcN-NLUEd8yeFkJoRndlBlj2mFMpyleGuXHFzlxDu2xD4auJ9G9gt2rlJ8g52rGTOGA3ncwUfGB_6k1zmcBzmhppPc_BH6ZVxSMoGRC4F3HGGlyhXWy3zOv6_SxfwJTvWDkp3vsK7JZL7b06tDE26o0zpr6c701nlg",
    rating: 4.98,
    reviewsCount: 184,
    completedJobsCount: 420,
    experienceYears: 9,
    responseMinutes: 5,
    verified: true,
    phone: "+998 90 234-56-78",
    city: "Toshkent",
    district: "Chilonzor",
    addressFull: "Toshkent, Chilonzor, Yunusobod",
    priceRange: {
      min: 150000,
      max: 450000,
      formatted: "150 000 so‘mdan",
    },
    distanceKm: 1.8,
    availableTime: "Hozir bo‘sh",
    isOnline: true,
    matchReason: "Toshkent bo'yicha eng tez yetib keluvchi santexnik mutaxassis",
    categoryIds: ["santexnika"],
    tags: ["Quvur almashtirish", "Issiq pol", "Katyo‘l"],
    warrantyMonths: 12,
    aboutText: "Har qanday murakkablikdagi santexnika ishlarini sifatli va kafolatli bajaraman.",
    ratingMetrics: {
      quality: 5.0,
      punctuality: 5.0,
      priceFairness: 4.9,
    },
    services: [],
    portfolio: [],
    reviews: [],
  },
  {
    id: "jahongir-olimov",
    slug: "jahongir-olimov",
    name: "Jahongir Olimov",
    title: "Klimat Mutaxassisi • 6 yillik tajriba",
    shortTitle: "Jahongir Usta",
    avatar: "https://lh3.googleusercontent.com/aida-public/AB6AXuAIN2H342xMzYIh-lfRhV0jbqWA3zXuv0v6_1--n5_hahaTTep-aRJf-qwjN8dXkC6KM_GzPN6QxgdSFT3vXtN87MrkF6OBaNrl-f_uOQhGriSnr-v7BUwjshcik8246NQYcoShd3z668LYHmfLX3iauYlgjQcz8eL0sIBVZFRRcb8yv5D8m2-maYhg6WJ94qncRDPXLniiwt58MB39DIW4-oiiRBNjBFFMkmz5oc9ZcCrMlFCou4Qm6g",
    coverImage: "https://lh3.googleusercontent.com/aida-public/AB6AXuClv5k6ZHlSJABG5tCAg0LKR3wDg7txCRnuz44M0A0RlNFEa3v7yKAz9_p2vGoxAfanewLDhlbqYgw4Jeu6sKvHgcN-NLUEd8yeFkJoRndlBlj2mFMpyleGuXHFzlxDu2xD4auJ9G9gt2rlJ8g52rGTOGA3ncwUfGB_6k1zmcBzmhppPc_BH6ZVxSMoGRC4F3HGGlyhXWy3zOv6_SxfwJTvWDkp3vsK7JZL7b06tDE26o0zpr6c701nlg",
    rating: 4.92,
    reviewsCount: 110,
    completedJobsCount: 156,
    experienceYears: 6,
    responseMinutes: 3,
    verified: true,
    phone: "+998 97 789-01-23",
    city: "Toshkent",
    district: "Shayxontohur",
    addressFull: "Toshkent, Shayxontohur, Olmazor",
    priceRange: {
      min: 180000,
      max: 350000,
      formatted: "180 000 so‘mdan",
    },
    distanceKm: 2.8,
    availableTime: "Bugun 16:00 dan",
    isOnline: true,
    matchReason: "Eng tezkor javob berish ko'rsatkichi (3 daqiqa)",
    categoryIds: ["konditsioner", "maishiy-texnika"],
    tags: ["Freon quyish", "Yuvish", "Muzlatgich"],
    warrantyMonths: 6,
    aboutText: "Freon to'ldirish, qochqinlarni aniqlash va zamonaviy inverter konditsionerlarni yuvish.",
    ratingMetrics: {
      quality: 4.9,
      punctuality: 4.9,
      priceFairness: 4.9,
    },
    services: [],
    portfolio: [],
    reviews: [],
  },
  {
    id: "bek-usta",
    slug: "bek-usta",
    name: "Bekzod Rustamov (Bek Usta)",
    title: "Sovutish tizimlari ustasi",
    shortTitle: "Bek Usta",
    avatar: "https://lh3.googleusercontent.com/aida-public/AB6AXuB831povt5TJCnQ3_6F0p145SqNk8EU636zHWig7U5S43GTUZwKeCqnXNyg48_tuUpwo82VRX3OI7QZXefmbx4KfwHxbFEesdfBHMj2wQqIgpU8xxxMLiYhy6c1apF-TvntBE75biaLmebGtwoC4_Zf7htbBD0LT8XmV7B9EbglT22tY8yS4waLLp76ylImM4MJIx62RjAxkv-k1QxxudbO6RER9CuGKr-WOAP4FMwngxPMDyaCrLpK9g",
    coverImage: "https://lh3.googleusercontent.com/aida-public/AB6AXuClv5k6ZHlSJABG5tCAg0LKR3wDg7txCRnuz44M0A0RlNFEa3v7yKAz9_p2vGoxAfanewLDhlbqYgw4Jeu6sKvHgcN-NLUEd8yeFkJoRndlBlj2mFMpyleGuXHFzlxDu2xD4auJ9G9gt2rlJ8g52rGTOGA3ncwUfGB_6k1zmcBzmhppPc_BH6ZVxSMoGRC4F3HGGlyhXWy3zOv6_SxfwJTvWDkp3vsK7JZL7b06tDE26o0zpr6c701nlg",
    rating: 4.88,
    reviewsCount: 98,
    completedJobsCount: 140,
    experienceYears: 5,
    responseMinutes: 10,
    verified: true,
    phone: "+998 91 345-67-89",
    city: "Toshkent",
    district: "Chilonzor",
    addressFull: "Toshkent, Chilonzor tumani",
    priceRange: {
      min: 90000,
      max: 260000,
      formatted: "90 000 – 260 000 so‘m",
    },
    distanceKm: 3.5,
    availableTime: "Bugun 20:00",
    isOnline: true,
    categoryIds: ["konditsioner"],
    tags: ["Freon", "Diagnostika", "Yuvish"],
    warrantyMonths: 3,
    aboutText: "Sovutish tizimlari ustasi. Halol va sifatli xizmat.",
    ratingMetrics: {
      quality: 4.8,
      punctuality: 4.9,
      priceFairness: 4.9,
    },
    services: [],
    portfolio: [],
    reviews: [],
  },
  {
    id: "davron-texnik",
    slug: "davron-texnik",
    name: "Davron Jo'rayev (Davron Texnik)",
    title: "Universal maishiy texnika ustasi",
    shortTitle: "Davron Texnik",
    avatar: "https://lh3.googleusercontent.com/aida-public/AB6AXuAFUu0Pw91jp6cac_VUKwThC30TGTZYCtupzAjuILHu1nwspCX3njYmIH0046KxRYFpVYG2jtsw4wFe7igjCGqj1SyhD4EpcyJc5dF6Z18a6VGYicpDq18NkIU7WJ_C6E1UdRccjpdJWwkNG5IZJnkmnIUN3G4x3SIRtW1Tr0Wc1R9GhIWgbsoCCZZfkYGpRaGINmnfZBdfMjuT-VytYjYpy95pSATYEVh9f5aMQikJ3pw76LFELGK7Nw",
    coverImage: "https://lh3.googleusercontent.com/aida-public/AB6AXuClv5k6ZHlSJABG5tCAg0LKR3wDg7txCRnuz44M0A0RlNFEa3v7yKAz9_p2vGoxAfanewLDhlbqYgw4Jeu6sKvHgcN-NLUEd8yeFkJoRndlBlj2mFMpyleGuXHFzlxDu2xD4auJ9G9gt2rlJ8g52rGTOGA3ncwUfGB_6k1zmcBzmhppPc_BH6ZVxSMoGRC4F3HGGlyhXWy3zOv6_SxfwJTvWDkp3vsK7JZL7b06tDE26o0zpr6c701nlg",
    rating: 4.75,
    reviewsCount: 64,
    completedJobsCount: 88,
    experienceYears: 4,
    responseMinutes: 20,
    verified: true,
    phone: "+998 99 876-54-32",
    city: "Toshkent",
    district: "Olmazor",
    addressFull: "Toshkent, Olmazor tumani",
    priceRange: {
      min: 70000,
      max: 220000,
      formatted: "70 000 – 220 000 so‘m",
    },
    distanceKm: 6.2,
    availableTime: "Ertaga 10:00",
    isOnline: false,
    categoryIds: ["konditsioner", "maishiy-texnika"],
    tags: ["Universal", "Diagnostika"],
    warrantyMonths: 1,
    aboutText: "Maishiy texnika va konditsioner ta'miri bo'yicha tajribali mutaxassis.",
    ratingMetrics: {
      quality: 4.7,
      punctuality: 4.7,
      priceFairness: 4.9,
    },
    services: [],
    portfolio: [],
    reviews: [],
  },
];
