# Generated by Django 5.2.15 on 2026-09-14 09:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('service_name', models.CharField(default="Konditsioner ta'miri", max_length=200)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('CREATED', 'Yaratildi'), ('CONFIRMED', 'Tasdiqlandi'), ('IN_TRANSIT', 'Usta yo‘lda'), ('IN_PROGRESS', 'Ish jarayonda'), ('COMPLETED', 'Bajarildi'), ('CANCELLED', 'Bekor qilindi')], db_index=True, default='IN_TRANSIT', max_length=20)),
                ('status_text', models.CharField(default='Usta yo‘lda', max_length=100)),
                ('scheduled_time', models.CharField(default='Bugun, 17:30 – 19:30', max_length=150)),
                ('estimated_arrival', models.CharField(default='17:50', max_length=50)),
                ('estimated_minutes_left', models.PositiveIntegerField(default=10)),
                ('vehicle_model', models.CharField(default='Cobalt', max_length=100)),
                ('vehicle_color', models.CharField(default='Oq', max_length=50)),
                ('vehicle_plate', models.CharField(default='01 A 777 BA', max_length=50)),
                ('destination_address', models.CharField(default='Chilonzor tumani, 9-mavze, 14-uy', max_length=255)),
                ('distance_km', models.FloatField(default=3.2)),
                ('payment_method', models.CharField(choices=[('CASH', 'Naqd pul'), ('CARD', 'Plastik karta'), ('ESCROW', 'Xavfsiz depozit')], default='ESCROW', max_length=20)),
                ('is_paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Buyurtma',
                'verbose_name_plural': 'Buyurtmalar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookingStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('old_status', models.CharField(max_length=20)),
                ('new_status', models.CharField(max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BookingTimelineStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('subtitle', models.CharField(blank=True, max_length=200)),
                ('timestamp_text', models.CharField(blank=True, max_length=50)),
                ('completed', models.BooleanField(default=False)),
                ('current', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
