# Generated by Django 5.2.15 on 2026-09-14 09:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('labor_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Xizmat haqi (so‘m)')),
                ('parts_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Ehtiyot qismlar narxi (so‘m)')),
                ('additional_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Qo‘shimcha xarajatlar (so‘m)')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Umumiy narx (so‘m)')),
                ('arrival_time', models.CharField(max_length=150, verbose_name='Yetib borish vaqti')),
                ('warranty', models.CharField(default='12 oy kafolat', max_length=150, verbose_name='Kafolat muddati')),
                ('notes', models.TextField(blank=True, verbose_name='Izoh')),
                ('status', models.CharField(choices=[('PENDING', 'Kutilmoqda'), ('ACCEPTED', 'Qabul qilindi'), ('REJECTED', 'Rad etildi'), ('EXPIRED', 'Muddati o‘tgan'), ('WITHDRAWN', 'Qaytarib olingan')], db_index=True, default='PENDING', max_length=20)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='providers.providerprofile', verbose_name='Usta')),
            ],
            options={
                'verbose_name': 'Smeta taklifi',
                'verbose_name_plural': 'Smeta takliflari',
                'ordering': ['-created_at'],
            },
        ),
    ]
