# Generated by Django 5.2.15 on 2026-09-14 09:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('NEW_REQUEST', 'Yangi buyurtma'), ('NEW_QUOTE', 'Yangi smeta taklifi'), ('QUOTE_ACCEPTED', 'Taklif qabul qilindi'), ('BOOKING_CONFIRMED', 'Buyurtma tasdiqlandi'), ('BOOKING_CANCELLED', 'Buyurtma bekor qilindi'), ('BOOKING_STARTED', 'Ish boshlandi'), ('BOOKING_COMPLETED', 'Ish yakunlandi'), ('NEW_MESSAGE', 'Yangi xabar'), ('NEW_REVIEW', 'Yangi sharh'), ('DISPUTE_UPDATED', 'Nizo holati yangilandi'), ('VERIFICATION_UPDATED', 'Verifikatsiya natijasi')], db_index=True, max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('data', models.JSONField(blank=True, default=dict)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
