# Generated by Django 5.2.15 on 2026-09-14 09:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequestAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_url', models.URLField(max_length=500, verbose_name='Fayl URL')),
                ('file_type', models.CharField(default='image', max_length=20)),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('size_bytes', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RequestStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('old_status', models.CharField(max_length=20)),
                ('new_status', models.CharField(max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('problem_description', models.TextField(verbose_name='Muammo tavsifi')),
                ('detected_issues', models.JSONField(blank=True, default=list)),
                ('answers', models.JSONField(blank=True, default=dict)),
                ('city', models.CharField(default='Toshkent', max_length=100)),
                ('district', models.CharField(default='Chilonzor', max_length=100)),
                ('address_text', models.CharField(max_length=255, verbose_name='Manzil')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('urgency', models.CharField(choices=[('URGENT', '⚡ Shoshilinch (1-2 soatda)'), ('TODAY', 'Bugun kun davomida'), ('TOMORROW', 'Ertaga qulay vaqtda')], default='URGENT', max_length=20)),
                ('urgency_text', models.CharField(default='⚡ Shoshilinch', max_length=100)),
                ('status', models.CharField(choices=[('DRAFT', 'Qoralama'), ('OPEN', 'Ochiq (Takliflar qabul qilinmoqda)'), ('MATCHED', 'Ustalar tavsiya etildi'), ('ASSIGNED', 'Usta biriktirildi'), ('IN_PROGRESS', 'Ish bajarilmoqda'), ('COMPLETED', 'Yakunlandi'), ('CANCELLED', 'Bekor qilindi'), ('DISPUTED', 'Nizo holatida')], db_index=True, default='OPEN', max_length=20)),
                ('has_audio', models.BooleanField(default=False)),
                ('audio_duration', models.CharField(blank=True, max_length=20)),
                ('audio_url', models.URLField(blank=True, max_length=500)),
                ('budget_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('budget_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('preferred_date', models.DateField(blank=True, null=True)),
                ('preferred_time_slot', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Xizmat buyurtmasi',
                'verbose_name_plural': 'Xizmat buyurtmalari',
                'ordering': ['-created_at'],
            },
        ),
    ]
