# Generated by Django 5.2.15 on 2026-09-14 09:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderAvailability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('weekday', models.PositiveSmallIntegerField(help_text='0=Dushanba, 6=Yakshanba')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProviderPortfolio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('location', models.CharField(blank=True, max_length=150)),
                ('image_url', models.URLField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Portfolio ishi',
                'verbose_name_plural': 'Portfolio ishlari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProviderService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('custom_name', models.CharField(max_length=150, verbose_name='Xizmat nomi')),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Narx (so‘m)')),
                ('badge', models.CharField(blank=True, max_length=50)),
                ('icon_name', models.CharField(default='Wrench', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Usta xizmati',
                'verbose_name_plural': 'Usta xizmatlari',
            },
        ),
        migrations.CreateModel(
            name='ProviderServiceArea',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('radius_km', models.PositiveIntegerField(default=15)),
            ],
        ),
        migrations.CreateModel(
            name='ProviderProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('display_name', models.CharField(max_length=150, verbose_name='Usta nomi')),
                ('title', models.CharField(max_length=200, verbose_name='To‘liq mutaxassislik')),
                ('short_title', models.CharField(blank=True, max_length=100, verbose_name='Qisqa mutaxassislik')),
                ('cover_image', models.URLField(blank=True, max_length=500, verbose_name='Muqova rasm URL')),
                ('about_text', models.TextField(blank=True, verbose_name='Usta haqida batafsil')),
                ('experience_years', models.PositiveIntegerField(default=1, verbose_name='Tajriba yillari')),
                ('rating_avg', models.DecimalField(db_index=True, decimal_places=2, default=5.0, max_digits=3, verbose_name='O‘rtacha reyting')),
                ('review_count', models.PositiveIntegerField(default=0, verbose_name='Sharhlar soni')),
                ('completed_jobs', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Bajarilgan ishlar soni')),
                ('response_minutes', models.PositiveIntegerField(default=30, verbose_name='Javob berish vaqti (daqiqa)')),
                ('verification_status', models.CharField(choices=[('PENDING', 'Tekshiruvda'), ('VERIFIED', 'Tasdiqlangan'), ('REJECTED', 'Rad etilgan'), ('EXPIRED', 'Muddati o‘tgan')], db_index=True, default='PENDING', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Kutilmoqda'), ('ACTIVE', 'Faol'), ('SUSPENDED', 'Vaqtinchalik to‘xtatilgan'), ('BLOCKED', 'Bloklangan')], db_index=True, default='ACTIVE', max_length=20)),
                ('city', models.CharField(default='Toshkent', max_length=100)),
                ('district_text', models.CharField(default='Chilonzor', max_length=100)),
                ('address_full', models.CharField(blank=True, max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('price_min', models.DecimalField(decimal_places=2, default=80000, max_digits=12)),
                ('price_max', models.DecimalField(decimal_places=2, default=350000, max_digits=12)),
                ('available_time', models.CharField(default='Bugun 17:00 dan boshlab', max_length=100)),
                ('is_online', models.BooleanField(db_index=True, default=True)),
                ('warranty_months', models.PositiveIntegerField(default=12)),
                ('quality_rating', models.DecimalField(decimal_places=2, default=4.9, max_digits=3)),
                ('punctuality_rating', models.DecimalField(decimal_places=2, default=4.8, max_digits=3)),
                ('price_fairness_rating', models.DecimalField(decimal_places=2, default=4.9, max_digits=3)),
                ('vehicle_model', models.CharField(default='Cobalt oq', max_length=100)),
                ('vehicle_plate', models.CharField(default='01 A 777 BA', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.district')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.region')),
            ],
            options={
                'verbose_name': 'Usta profili',
                'verbose_name_plural': 'Ustalar profillari',
                'ordering': ['-rating_avg', '-completed_jobs'],
            },
        ),
    ]
