# Generated by Django 5.2.15 on 2026-09-14 09:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('locations', '0002_initial'),
        ('providers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='providerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='provider_profile', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi hisobi'),
        ),
        migrations.AddField(
            model_name='providerportfolio',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio', to='providers.providerprofile'),
        ),
        migrations.AddField(
            model_name='provideravailability',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='providers.providerprofile'),
        ),
        migrations.AddField(
            model_name='providerservice',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='providers.providerprofile'),
        ),
        migrations.AddField(
            model_name='providerservice',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.service'),
        ),
        migrations.AddField(
            model_name='providerservicearea',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.district'),
        ),
        migrations.AddField(
            model_name='providerservicearea',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_areas', to='providers.providerprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='provideravailability',
            unique_together={('provider', 'weekday')},
        ),
        migrations.AlterUniqueTogether(
            name='providerservicearea',
            unique_together={('provider', 'district')},
        ),
    ]
