# Generated by Django 5.2.15 on 2026-09-14 09:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisputeEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_url', models.URLField(max_length=500)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(max_length=200, verbose_name='Nizo sababi')),
                ('description', models.TextField(verbose_name='Batafsil tavsif')),
                ('status', models.CharField(choices=[('OPEN', 'Ochiq'), ('UNDER_REVIEW', 'Ko‘rib chiqilmoqda'), ('RESOLVED', 'Hal qilindi'), ('REJECTED', 'Rad etildi')], db_index=True, default='OPEN', max_length=20)),
                ('resolution', models.CharField(blank=True, choices=[('CUSTOMER_FAVOR', 'Mijoz foydasiga (Pullar qaytariladi)'), ('PROVIDER_FAVOR', 'Usta foydasiga'), ('PARTIAL', 'Qisman qaytarish')], max_length=20, null=True)),
                ('resolution_note', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='bookings.booking')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
