# Generated by Django 5.2.15 on 2026-09-14 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conversations', '0001_initial'),
        ('service_requests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='service_requests.servicerequest'),
        ),
        migrations.AddField(
            model_name='conversationparticipant',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='conversations.conversation'),
        ),
    ]
