# Generated by Django 5.2.15 on 2026-09-14 09:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='Toifa nomi')),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('icon', models.CharField(default='Wrench', max_length=50, verbose_name='Ikonka nomi')),
                ('image', models.URLField(blank=True, max_length=500, verbose_name='Rasm URL')),
                ('masters_count', models.PositiveIntegerField(default=0, verbose_name='Ustalar soni')),
                ('featured', models.BooleanField(default=False, verbose_name='Asosiy ekranda ko‘rsatish')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='catalog.servicecategory', verbose_name='Yuqori toifa')),
            ],
            options={
                'verbose_name': 'Xizmat toifasi',
                'verbose_name_plural': 'Xizmat toifalari',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='Xizmat nomi')),
                ('slug', models.SlugField(max_length=150)),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('base_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Boshlang‘ich narx (so‘m)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='catalog.servicecategory', verbose_name='Kategoriya')),
            ],
            options={
                'verbose_name': 'Xizmat',
                'verbose_name_plural': 'Xizmatlar',
                'ordering': ['name'],
                'unique_together': {('category', 'slug')},
            },
        ),
    ]
