# Generated by Django 5.2.15 on 2026-09-14 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matching', '0002_initial'),
        ('service_requests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchingscore',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matching_scores', to='service_requests.servicerequest'),
        ),
        migrations.AlterUniqueTogether(
            name='matchingscore',
            unique_together={('request', 'provider')},
        ),
    ]
