# Generated by Django 5.2.15 on 2026-09-14 09:45

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Umumiy baho (1-5)')),
                ('quality_rating', models.DecimalField(decimal_places=2, default=5.0, max_digits=3)),
                ('punctuality_rating', models.DecimalField(decimal_places=2, default=5.0, max_digits=3)),
                ('price_rating', models.DecimalField(decimal_places=2, default=5.0, max_digits=3)),
                ('service_title', models.CharField(default="Konditsioner ta'miri", max_length=200)),
                ('location_text', models.CharField(default='Chilonzor', max_length=150)),
                ('comment', models.TextField(verbose_name='Mijoz fikri')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='bookings.booking', verbose_name='Buyurtma')),
            ],
            options={
                'verbose_name': 'Sharh va baho',
                'verbose_name_plural': 'Sharhlar va baholar',
                'ordering': ['-created_at'],
            },
        ),
    ]
