# Generated by Django 5.2.15 on 2026-09-14 09:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='To‘lov miqdori (so‘m)')),
                ('currency', models.CharField(default='UZS', max_length=3)),
                ('provider', models.CharField(choices=[('ESCROW', 'Usta Top Xavfsiz Hisob (Escrow)'), ('PAYME', 'Payme'), ('CLICK', 'Click'), ('UZUM', 'Uzum Pay'), ('CASH', 'Naqd pul')], default='ESCROW', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Kutilmoqda'), ('PROCESSING', 'Jarayonda'), ('SUCCEEDED', 'Muvaffaqiyatli to‘landi'), ('FAILED', 'Xatolik yuz berdi'), ('CANCELLED', 'Bekor qilindi'), ('REFUNDED', 'Qaytarildi')], db_index=True, default='PENDING', max_length=20)),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=150)),
                ('idempotency_key', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='bookings.booking')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
